#!/bin/bash
set -v

rm -r output*.txt;

#testing arguments exceptions
java DeleteField 2 - - 3 4 5

#testing a file that is not there
java DeleteField 4 INPUTFILE.txt outputFile1.txt

#testing to an ouput file that already exists
java DeleteField 3 inputFile.txt inputFile.txt

#testing properly with files
java DeleteField 3 inputFile.txt outputFile2.txt

#testing the standard input
java DeleteField 1 - outputFile3.txt<<END
MON	TUE	WED	THUR	FRI	SAT	SUN
01 	02	03	04	05	06	07
08	09	10	11	12	13	14
15	16	17	18	19	20	21

END

#testing the standard output
java DeleteField 3 inputFile.txt -

#testing the standard input and output
java DeleteField 1 - -<<END
MON	TUE	WED	THUR	FRI	SAT	SUN
01 	02	03	04	05	06	07
08	09	10	11	12	13	14
15	16	17	18	19	20	21

END
